module.exports = {
	ADMINISTRATOR: 'Администратор',
	CREATE_INSTANT_INVITE: 'Создавать экспресс приглашения',
	KICK_MEMBERS: 'Кикать участников',
	BAN_MEMBERS: 'Банить участников',
	MANAGE_CHANNELS: 'Управлять каналами',
	MANAGE_GUILD: 'Управлять сервером',
	ADD_REACTIONS: 'Добавлять реакции',
	VIEW_AUDIT_LOG: 'Список аудита',
	PRIORITY_SPEAKER: 'Priority speaker',
	VIEW_CHANNEL: 'Просмотр каналов',
	SEND_MESSAGES: 'Писать сообщения',
	SEND_TTS_MESSAGES: 'Писать tts сообщения',
	MANAGE_MESSAGES: 'Управлять сообщениями',
	EMBED_LINKS: 'Отправлять ссылки',
	ATTACH_FILES: 'Приклеплять файлы',
	READ_MESSAGE_HISTORY: 'Читать историю сообщений',
	MENTION_EVERYONE: 'Упомянуть everyone',
	USE_EXTERNAL_EMOJIS: 'Использовать посторонние эмоджи',
	CONNECT: 'Подключиться к голосовому каналу',
	SPEAK: 'Говорить',
	STREAM: 'Стримить',
	MUTE_MEMBERS: 'Заглушать пользователей',
	DEAFEN_MEMBERS: 'Заглушать звук пользователям',
	MOVE_MEMBERS: 'Перемещать пользователей',
	USE_VAD: 'Голосовая активность',
	CHANGE_NICKNAME: 'Изменять никнейм',
	MANAGE_NICKNAMES: 'Управлять никнеймами',
	MANAGE_ROLES: 'Управлять ролями',
	MANAGE_WEBHOOKS: 'Управлять вебхуками',
	MANAGE_EMOJIS: 'Управлять эмоджи'
};
